apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 5m
  path: ./prometheus
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-workloads
