apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  releaseName: thanos
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "77.0.1"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    prometheus:
      prometheusSpec:
        retention: 10d
    alertmanager:
      alertmanagerSpec:
        replicas: 4    
    grafana:
      adminUser: admin
      adminPassword: admin
  valuesFiles:
    - values-prometheus.yaml    

