apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  releaseName: thanos
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "77.0.1"  # pin version if desired
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: values-prometheus
      valuesKey: values.yaml
