apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-flux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-flux
  template:
    metadata:
      labels:
        app: hello-flux
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ["sh", "-c", "while true; do echo 'Hello Flux!'; sleep 10; done"]
