apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  releaseName: thanos
  interval: 5m
  chart:
    spec:
      chart: ./kube-prometheus-stack
      sourceRef:
        kind: GitRepository
        name: flux-workloads
        namespace: flux-system
      version: 77.0.1
  values:
    alertmanager:
      alertmanagerSpec:
        replicas: 2
    prometheus:
      prometheusSpec:
        retention: 10d
