apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  releaseName: kube-prometheus-stack
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack   # chart name inside repo
      version: 77.0.1               # pin version you want
      sourceRef:
        kind: HelmRepository
        name: prometheus-community  # match the HelmRepository above
        namespace: flux-system
  values:
    alertmanager:
      alertmanagerSpec:
        replicas: 2
    prometheus:
      prometheusSpec:
        retention: 10d
