# releases/minio-helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: minio
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: minio
      version: 5.x.x # check latest available
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  values:
    mode: standalone
    accessKey: minio
    secretKey: minio123
    persistence:
      enabled: true
      size: 20Gi
