apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-objstore
  namespace: monitoring
data:
  objstore.yml: |
    type: S3
    config:
      bucket: "thanos"
      endpoint: "minio-minio.minio.svc.cluster.local:9000"
      access_key: "minio"
      secret_key: "minio123"
      insecure: true
