apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: thanos-query
  namespace: monitoring
spec:
  releaseName: thanos-query
  interval: 5m
  chart:
    spec:
      chart: thanos
      version: 17.3.1
      sourceRef:
        kind: HelmRepository
        name: bitnami-oci
        namespace: flux-system
  values:
    query:
      http:
        listenAddress: "0.0.0.0:9090"
      grpc:
        listenAddress: "0.0.0.0:10901"
      storeGatewayAddresses:
        - "prometheus-kube-prometheus-stack-prometheus-0.monitoring.svc.cluster.local:10901"
      logLevel: info
    service:
      type: ClusterIP
      port: 9090
