apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  chart:
    spec:
      chart: bitnami/thanos      # Corrected chart reference
      version: 17.3.1           # Correct version
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 10m  # Set the interval (e.g., 10 minutes)
