apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: thanos-query
  namespace: monitoring
spec:
  chart:
    spec:
      chart: thanos-query
      version: 17.3.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 10m  # Set the interval (e.g., 10 minutes)
